### ISSUE TITLE
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.

### ISSUE THREAD

**Issue by Polm90** [NeutrinosPlatform/cordova-plugin-mobile-ocr#15]
When I add the plugin in the ios platform, i receive this warning (cordova 9.0.0 and cordova-ios 5.0.1). Plugin version 3.1.1

**Comment by ChrisTomAlx** [comment]
Hey @Polm90 . Yea the latest cordova 9.0.0 added a new tag for adding cocoapod frameworks. But since older cordova versions won't support this. I won't be switching to this tag atleast for a while. In the meantime, it is just a deprecation notice and it won't affect you in any way atleast for a few more releases of cordova.  Although if you absolutely don't want to see it you can downgrade to cordova@8.x.x by doing the following :-

- `npm uninstall -g cordova`

- `npm install -g cordova@8.x.x`

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by Polm90** [comment]
Thank you.

I've should label it differently (sorry, I forgot to change the label): I only wanted to inform you about the warning :)

**Comment by ChrisTomAlx** [comment]
No worries. Always a pleasure to help.
Let me know if you run into any troubles.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
