### ISSUE TITLE
How do i pass 4 arguments ?

### ISSUE THREAD

**Issue by ChaminThilakarathne** [NeutrinosPlatform/cordova-plugin-mobile-ocr#24]
![Untitled](https://user-images.githubusercontent.com/25498284/67084976-9f948580-f1bb-11e9-9fe5-0d5bf4a5daab.png)

**Comment by ChrisTomAlx** [comment]
Hey @Chamiyalt 
Where are you getting this documentation from? Also what is plugin version are you using?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChaminThilakarathne** [comment]
cordova-plugin-mobile-ocr 3.1.1 "Textocr"

**Comment by ChaminThilakarathne** [comment]
this is the documentation which i followed https://ionicframework.com/docs/native/ocr#usage

**Comment by ChrisTomAlx** [comment]
I did not create that documentation or the interface ionic uses.
But as far as I can tell, you don't need to pass in success and failure. 
`OCR.recText` is a promise function, so you can just look for the resolve and reject, instead of passing in success and error callback functions.

So I guess the function call might look something like (got this from ionic docs) :-
```js
this.ocr.recText(OCRSourceType.NORMFILEURL, "file://path/to/image.png")
  .then((res: OCRResult) => console.log(JSON.stringify(res)))
  .catch((error: any) => console.error(error));
```

The [link ](https://ionicframework.com/docs/native/ocr#usage)you provided also backs up my claim. There is an example there. Try using the same example.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChaminThilakarathne** [comment]
It was worked. Thanks a lot.

**Comment by ChrisTomAlx** [comment]
Awesome!

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
