### ISSUE TITLE
Blocks definition

### ISSUE THREAD

**Issue by nemcko16** [NeutrinosPlatform/cordova-plugin-mobile-ocr#6]
I need to scan only several blocks of the picture. E.g. ID card. Is it possible to define the position of blocks and get OCR?

**Comment by ChrisTomAlx** [comment]
Hey @nemcko16 
Thanks for the interest in our plugin :)
Please use the [ml-text plugin](https://github.com/NeutrinosPlatform/cordova-plugin-ml-text) for this.
If you run into trouble, raise an issue there and I will be right along to help you. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Or if you would prefer using this plugin because it is more straight forward, You can crop sections of the image you want (using another plugin or canvas in js) then pass the base64 or imageURI of each of these sections individually into the plugin one after the other. Bit hacky but should work :) 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
